#!/usr/bin/env ruby
require 'date'
require 'time'
p="%02d"
def current()
if running=`watson status -p |grep master`.chop=="master" ;then
  time=`watson status |grep master`.chop.split('(')[1].split('+')[0]
  x=Time.strptime(time,'%Y.%m.%d %H:%M:%S') 
  curr=Time.now-x;
  puts("#{"%02d"%(curr.to_i/60)}:#{"%02d"%(curr.to_i%60)}")
else 
  puts("00:00")
end
end
def today()
 today=`watson report --day -p master|grep Total`
 today=today.chop.split(' ') unless today.nil?
 today=today.select{ |date| /[0-9][0-9][m,s,h]/=~date.to_s }
 today.each{|date|date[2]=''}
 while today.length < 3 do
  today.insert(0,"00")
 end
 puts("+#{"%02d"%today[0].to_i}:#{"%02d"%today[1].to_i}:#{"%02d"%today[2].to_i}")
end

  running=`watson status -p |grep master`.chop
  current() if ARGV[0]=="current"
  today() if ARGV[0]=="today"
